add label filter
rancher/scheduler pull request #35
Opened 2017-02-08 17:14 UTC by StrongMonkey

2017-02-08 17:24 UTC, StrongMonkey commented
This pr will support require_any logic.

2017-02-13 16:54 UTC, cjellick commented
@StrongMonkey please open an issue for 1.5 for documenting this feature

2017-02-13 17:38 UTC, deniseschannon commented
https://github.com/rancher/rancher/issues/7795

2017-02-13 17:45 UTC, deniseschannon commented
https://github.com/rancher/rancher/issues/7254

2017-02-15 20:59 UTC, StrongMonkey commented
@cjellick this pr is also ready to be reviewed now.

2017-02-16 16:07 UTC, cjellick requested changes

2017-02-16 16:07 UTC, cjellick commented on scheduler/types.go
> +	labelPool = "labelPool"
Can you move this next to the otehr Pool constants in the scheduler.go?

2017-02-16 16:07 UTC, cjellick commented on scheduler/scheduler.go
> +	logrus.Infof("return hosts %v", filteredHosts)
We already log the hosts we are returning when we log the entire event response. Can you remove this log line? I want to a little more protective about over-logging.

2017-02-16 16:07 UTC, cjellick commented on scheduler/scheduler_label_test.go
> +}
Can you add a couple test scenarios for sending more than one context is a request? Meaning the contexdt would looklike []Context{conA, conB}

2017-02-16 16:07 UTC, cjellick commented on scheduler/label_filter.go
> +	if qualify {
you could just return qulify

2017-02-16 18:33 UTC, cjellick commented
LGTM

2017-02-16 18:34 UTC, cjellick approved these changes

2017-02-16 18:34 UTC, merged